version: '2'

volumes:
   homefs-agave-model:

services:

  agave-model:
    # Uncomment the next lines if you want to build
    build:
        context: ../docker
        dockerfile: Dockerfile
    image: stevenrbrandt/agave-model
    environment:
      - PORT=8002
    container_name: cmr
    user: jovyan
    ports:
      - '8002:8002'
    volumes:
      - homefs-agave-model:/home/jovyan
