version: '2'

volumes:
   homefs-agave-model:

services:
  agave-model:
    image: lsucrc/agave-model
    container_name: cmr
    user: jovyan
    ports:
      - '8003:8003'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - homefs-agave-model:/home/jovyan
