version: '2'

volumes:
   homefs-agave-model:

services:

  agave-model:
    # Uncomment the next lines if you want to build
    #build:
    #    context: .
    #    dockerfile: Dockerfile
    image: lsucrc/agave-model
    container_name: cmr
    user: jovyan
    ports:
      - '8003:8003'
    volumes:
      - homefs-agave-model:/home/jovyan

  paraview:
    build:
        context: .
        dockerfile: para.docker
    image: paraviewweb
    container_name: para
    user: jovyan
    ports:
      - '8005:80'
    volumes:
      - homefs-agave-model:/home/jovyan
